### ISSUE TITLE
Climate matching issue due to taxonomic synonyms ?

### ISSUE THREAD

**Issue by adrienlatli** [inbo/riparias-prep#10]
@SanderDevisscher, @timadriaens  and @RomainWilleput 

Hello,
With Romain, we found a potential problem regarding the filters that were applied to GBIF occurrences for climate matching.
For several species, we have large differences between the number of observations in  GBIF and the number of observations take into account in the climate matching analysis.
For example, the specie Faxonius neglectus has only 5 viable observations in our climate matching table (https://github.com/inbo/riparias-prep/blob/a1f20d61681c3941b1858b38b2b29c4339571b92/data/output/data_overlay_future_10km.csv) but in GBIF we found more than 400 observations (https://www.gbif.org/species/8848320) with a lot of current human observations.

Maybe you have used for the CM analysis the GBIF code of Orconectes neglectus, a synonyms of Faxonius neglectus, which has a pretty low number of human observations.

Do GBIF codes allow to link species by their synonyms ? Or the error coming from somewhere else?

**Comment by SanderDevisscher** [comment]
@adrienlatli I looked at the [white list](https://github.com/inbo/riparias-prep/blob/master/data/raw/White%20list%20proposal%20for%20aquarium%20crayfish%20GBIF%2022092020.xlsx) (the list I used to download the gbif occurrences) and only _Orconectes neglectus_ is listed. 

If you guys could look at the list and change the taxonkeys of the synonyms (_Orconectes neglectus_ ~ 2227071) to these of the accepted species (_Faxonius neglectus_ ~ 8848320). I think the synonyms will be included in the download.  Adding `distinct(gbif_id, keep_all = TRUE)`  to the subset should remove any duplicates. 

Steps:

- [ ] Create branch in github online @adrienlatli or @RomainWilleput <sup>1</sup>
- [ ] Sync local github repository @adrienlatli or @RomainWilleput <sup>1</sup>
- [ ] Select created branch @adrienlatli or @RomainWilleput <sup>1</sup>
- [ ] Update, commit and push changes to white list @adrienlatli or @RomainWilleput <sup>1</sup>
- [ ] Add duplicates filter @SanderDevisscher 
- [ ] Rerun scripts @SanderDevisscher 
- [ ] Create PR @SanderDevisscher 
- [ ] Approve and merge PR @timadriaens, @adrienlatli and/or @RomainWilleput  

<sup>1</sup>alternatively you can do these changes outside the github workflow and drag and drop the new list as a comment to this issue. I'll commit and push it then.  

PS: @timadriaens @adrienlatli @RomainWilleput do you expect the list to change frequently in the near future ? ifso I would suggest changing the list into a .gsheet. This allows for a more dynamic approach to a frequently changing list. However this requires a small rewrite to the script to be active.

**Comment by RomainWilleput** [comment]
@SanderDevisscher

**Comment by RomainWilleput** [comment]
Hello @SanderDevisscher 
With Adrien, we wonder if it is not more interesting to make all the crayfish species of GBIF pass in the CM analysis in order to have a complete database for the Alert List but also for the continuation of the project (White List, ...).
I tried to download the "GBIF Backbone Taxonomy" .tsv but the file is too big to be opened with Excel.
https://www.gbif.org/fr/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
Is there another solution ?
As a reminder, the 3 families of crayfish are Astacidae, Cambaridae and Parastacidae.
https://www.gbif.org/species/8022
https://www.gbif.org/species/4479
https://www.gbif.org/species/8670
Is it possible to extract all the species of these 3 families on GBIF and to pass the whole list to the CM analysis ?
To make the Alert List, I will select the accepted species in the CM analysis results for each species available in aquarium stores.
Thanks in advance

**Comment by SanderDevisscher** [comment]
> Is it possible to extract all the species of these 3 families on GBIF and to pass the whole list to the CM analysis ?
> To make the Alert List, I will select the accepted species in the CM analysis results for each species available in aquarium stores.

Yes this is possible see also issue #5

**Comment by RomainWilleput** [comment]
> Yes this is possible see also issue #5

Perfect, that would be really nice!
About synonyms, I think that the accepted species includes all occurrences of synonymous species. That should not be a problem.
